# Generated by Django 5.0.3 on 2024-06-10 16:18

import django.db.models.deletion
import helpers.dates
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='date_updated')),
                ('date_deleted', models.DateTimeField(db_column='date_deleted', default=helpers.dates.dt_end_date)),
                ('oid', models.UUIDField(db_column='oid', default=uuid.uuid4, unique=True)),
                ('fullname', models.CharField(db_column='fullname', db_index=True, max_length=150)),
                ('username', models.CharField(db_column='username', db_index=True, max_length=50, unique=True)),
                ('email', models.CharField(db_column='email', db_index=True, max_length=50)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('password_changed', models.DateTimeField(db_column='password_changed', default=None, null=True)),
            ],
            options={
                'db_table': 'tb_users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='date_updated')),
                ('date_deleted', models.DateTimeField(db_column='date_deleted', default=helpers.dates.dt_end_date)),
                ('oid', models.UUIDField(db_column='oid', default=uuid.uuid4, unique=True)),
                ('file', models.FileField(db_column='file', upload_to='')),
                ('filename', models.CharField(db_column='filename', db_index=True, max_length=255)),
                ('extension', models.CharField(db_column='extension', max_length=10)),
                ('size', models.IntegerField(db_column='size')),
                ('secret_key', models.CharField(blank=True, db_column='secret_key', max_length=255)),
            ],
            options={
                'db_table': 'tb_files',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='date_updated')),
                ('date_deleted', models.DateTimeField(db_column='date_deleted', default=helpers.dates.dt_end_date)),
                ('oid', models.UUIDField(db_column='oid', default=uuid.uuid4, unique=True)),
                ('rolename', models.CharField(db_column='rolename', db_index=True, max_length=20)),
            ],
            options={
                'db_table': 'tb_roles',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='date_updated')),
                ('date_deleted', models.DateTimeField(db_column='date_deleted', default=helpers.dates.dt_end_date)),
                ('oid', models.UUIDField(db_column='oid', default=uuid.uuid4, unique=True)),
                ('action', models.CharField(db_column='action', db_index=True, max_length=255)),
                ('issued', models.DateTimeField(auto_now_add=True, db_column='issued')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_recent_activities',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='database.role'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='date_created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='date_updated')),
                ('date_deleted', models.DateTimeField(db_column='date_deleted', default=helpers.dates.dt_end_date)),
                ('oid', models.UUIDField(db_column='oid', default=uuid.uuid4, unique=True)),
                ('key', models.CharField(db_column='key', db_index=True, max_length=255)),
                ('vector', models.CharField(db_column='vector', max_length=255)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('status', models.CharField(choices=[('ENCRYPTED', 'ENCRYPTED'), ('DECRYPTED', 'DECRYPTED'), ('PENDING', 'PENDING'), ('FAILURE', 'FAILURE')], db_column='status', max_length=10)),
                ('file', models.ForeignKey(db_column='file_id', on_delete=django.db.models.deletion.CASCADE, to='database.file')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_transactions',
                'abstract': False,
            },
        ),
    ]
