# Generated by Django 5.0.6 on 2024-06-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='tw_color',
            field=models.CharField(choices=[('ENCRYPTION', 'text-blue-600'), ('DECRYPTION', 'text-orange-500'), ('FILE_DELETE', 'text-red-700'), ('ACCOUNT_UPDATE', 'text-sky-600')], db_column='tw_color', max_length=255),
        ),
    ]
