# Generated by Django 5.0.3 on 2024-06-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(db_column='filename', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='action',
            field=models.CharField(db_column='action', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='rolename',
            field=models.CharField(db_column='rolename', db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='key',
            field=models.CharField(db_column='key', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_column='email', db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(db_column='fullname', db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='username', db_index=True, max_length=50),
        ),
    ]
