# Generated by Django 5.0.3 on 2024-06-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_file_filename_alter_recentactivity_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(db_column='file', upload_to=''),
        ),
    ]
